colors: false

logging:

  # path to a file where cli logs will be saved.
  filename: /var/folders/m3/0876g44577jdfsmm_w1_7qgh0000gq/T/cloudify-an.auger/cloudify-cli.log

  # configuring level per logger
  loggers:

    # main logger of the cli. provides basic descriptions for executed operations.
    cloudify.cli.main: info

    # rest client http logs, including headers.
    cloudify.rest_client.http: info
